

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class LocalSqlServer : DbContext
{
    public LocalSqlServer()
        : base("name=LocalSqlServer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<as_categories> as_categories { get; set; }

    public virtual DbSet<as_dataTypes> as_dataTypes { get; set; }

    public virtual DbSet<as_menu> as_menu { get; set; }

    public virtual DbSet<as_menuRoles> as_menuRoles { get; set; }

    public virtual DbSet<as_profileProperties> as_profileProperties { get; set; }

    public virtual DbSet<as_profilePropertyValues> as_profilePropertyValues { get; set; }

    public virtual DbSet<as_rights> as_rights { get; set; }

    public virtual DbSet<as_rightsRoles> as_rightsRoles { get; set; }

    public virtual DbSet<as_settingAvailableValues> as_settingAvailableValues { get; set; }

    public virtual DbSet<as_settingCategories> as_settingCategories { get; set; }

    public virtual DbSet<as_settings> as_settings { get; set; }

    public virtual DbSet<as_statuses> as_statuses { get; set; }

    public virtual DbSet<as_statusLog> as_statusLog { get; set; }

    public virtual DbSet<as_trace> as_trace { get; set; }

    public virtual DbSet<as_rightCategories> as_rightCategories { get; set; }

    public virtual DbSet<crm_clients> crm_clients { get; set; }

    public virtual DbSet<crm_clientStatuses> crm_clientStatuses { get; set; }

    public virtual DbSet<crm_orderItems> crm_orderItems { get; set; }

    public virtual DbSet<crm_orders> crm_orders { get; set; }

    public virtual DbSet<crm_orderStatuses> crm_orderStatuses { get; set; }

    public virtual DbSet<crm_sources> crm_sources { get; set; }

    public virtual DbSet<ct_products> ct_products { get; set; }

    public virtual DbSet<as_comments> as_comments { get; set; }

    public virtual DbSet<as_texts> as_texts { get; set; }

    public virtual DbSet<as_userActions> as_userActions { get; set; }

    public virtual DbSet<hr_humans> hr_humans { get; set; }

    public virtual DbSet<hr_humanSpecializations> hr_humanSpecializations { get; set; }

    public virtual DbSet<hr_sources> hr_sources { get; set; }

    public virtual DbSet<hr_specializations> hr_specializations { get; set; }

    public virtual DbSet<hr_statuses> hr_statuses { get; set; }

    public virtual DbSet<fin_channels> fin_channels { get; set; }

    public virtual DbSet<fin_contragents> fin_contragents { get; set; }

    public virtual DbSet<fin_finances> fin_finances { get; set; }

    public virtual DbSet<fin_statuses> fin_statuses { get; set; }

    public virtual DbSet<fin_types> fin_types { get; set; }

    public virtual DbSet<tt_projects> tt_projects { get; set; }

    public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }

    public virtual DbSet<art_newsType> art_newsType { get; set; }

    public virtual DbSet<as_profileMenu> as_profileMenu { get; set; }

    public virtual DbSet<as_mail> as_mail { get; set; }

    public virtual DbSet<as_mailAttachment> as_mailAttachment { get; set; }

    public virtual DbSet<as_mailAttachmentType> as_mailAttachmentType { get; set; }

    public virtual DbSet<as_mailLog> as_mailLog { get; set; }

    public virtual DbSet<art_news> art_news { get; set; }

    public virtual DbSet<as_favorites> as_favorites { get; set; }

    public virtual DbSet<as_mt_metrics> as_mt_metrics { get; set; }

    public virtual DbSet<as_mt_metricTypes> as_mt_metricTypes { get; set; }

    public virtual DbSet<as_images> as_images { get; set; }

    public virtual DbSet<as_textMistakes> as_textMistakes { get; set; }

    public virtual DbSet<as_userCheckItems> as_userCheckItems { get; set; }

    public virtual DbSet<as_userChecks> as_userChecks { get; set; }

    public virtual DbSet<as_userCheckSet> as_userCheckSet { get; set; }

    public virtual DbSet<as_files> as_files { get; set; }

    public virtual DbSet<as_ctrl> as_ctrl { get; set; }

    public virtual DbSet<calc_calcs> calc_calcs { get; set; }

    public virtual DbSet<calc_parameters> calc_parameters { get; set; }

    public virtual DbSet<recl_items> recl_items { get; set; }

    public virtual DbSet<recl_itemStatuses> recl_itemStatuses { get; set; }

    public virtual DbSet<as_hotkeys> as_hotkeys { get; set; }

    public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }

    public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }

    public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }

    public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }

    public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }

    public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }

    public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }

    public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }

    public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }

    public virtual DbSet<sysdiagram> sysdiagrams { get; set; }

    public virtual DbSet<Location> Locations { get; set; }

    public virtual DbSet<as_opinion> as_opinion { get; set; }

    public virtual DbSet<ps_specsPartners> ps_specsPartners { get; set; }

    public virtual DbSet<ps_partners> ps_partners { get; set; }

    public virtual DbSet<ps_specs> ps_specs { get; set; }

    public virtual DbSet<ps_statuses> ps_statuses { get; set; }

    public virtual DbSet<imp_itemLog> imp_itemLog { get; set; }

    public virtual DbSet<imp_items> imp_items { get; set; }

    public virtual DbSet<gr_site> gr_site { get; set; }

    public virtual DbSet<doc_docLogs> doc_docLogs { get; set; }

    public virtual DbSet<doc_docVersions> doc_docVersions { get; set; }

    public virtual DbSet<doc_docStatuses> doc_docStatuses { get; set; }

    public virtual DbSet<doc_docTypes> doc_docTypes { get; set; }

    public virtual DbSet<doc_docTypeTemplates> doc_docTypeTemplates { get; set; }

    public virtual DbSet<doc_docs> doc_docs { get; set; }

    public virtual DbSet<as_sqlGet> as_sqlGet { get; set; }

    public virtual DbSet<as_sqlRole> as_sqlRole { get; set; }

    public virtual DbSet<cl_listInstanceItems> cl_listInstanceItems { get; set; }

    public virtual DbSet<cl_listInstances> cl_listInstances { get; set; }

    public virtual DbSet<cl_listItems> cl_listItems { get; set; }

    public virtual DbSet<cl_lists> cl_lists { get; set; }

    public virtual DbSet<SmallDataTest> SmallDataTest { get; set; }

    public virtual DbSet<proc_processes> proc_processes { get; set; }

    public virtual DbSet<proc_processItems> proc_processItems { get; set; }

    public virtual DbSet<Mikhailova_contagents> Mikhailova_contagents { get; set; }

    public virtual DbSet<Mikhailova_contracts> Mikhailova_contracts { get; set; }

    public virtual DbSet<Mikhailova_invoices> Mikhailova_invoices { get; set; }

    public virtual DbSet<Mikhailova_mails> Mikhailova_mails { get; set; }

    public virtual DbSet<Mikhailova_statuses_contracts> Mikhailova_statuses_contracts { get; set; }

    public virtual DbSet<Mikhailova_statuses_invoces> Mikhailova_statuses_invoces { get; set; }

    public virtual DbSet<Mikhailova_statuses_mails> Mikhailova_statuses_mails { get; set; }

    public virtual DbSet<Mikhailova_docTypes> Mikhailova_docTypes { get; set; }

    public virtual DbSet<Mikhailova_docTypeTemplates> Mikhailova_docTypeTemplates { get; set; }

    public virtual DbSet<tst_cars> tst_cars { get; set; }

    public virtual DbSet<tst_drivers> tst_drivers { get; set; }

    public virtual DbSet<gl_docStatuses> gl_docStatuses { get; set; }

    public virtual DbSet<gl_docTypes> gl_docTypes { get; set; }

    public virtual DbSet<gl_contragents> gl_contragents { get; set; }

    public virtual DbSet<gurevskiy_contracts> gurevskiy_contracts { get; set; }

    public virtual DbSet<gurevskiy_contractStatuses> gurevskiy_contractStatuses { get; set; }

    public virtual DbSet<gurevskiy_contractTypes> gurevskiy_contractTypes { get; set; }

    public virtual DbSet<gurevskiy_invoices> gurevskiy_invoices { get; set; }

    public virtual DbSet<gurevskiy_invoiceStatuses> gurevskiy_invoiceStatuses { get; set; }

    public virtual DbSet<gurevskiy_mails> gurevskiy_mails { get; set; }

    public virtual DbSet<gurevskiy_mailStatuses> gurevskiy_mailStatuses { get; set; }

    public virtual DbSet<gurevskiy_partner> gurevskiy_partner { get; set; }

    public virtual DbSet<pdv_contractors> pdv_contractors { get; set; }

    public virtual DbSet<pdv_documentStatuses> pdv_documentStatuses { get; set; }

    public virtual DbSet<pdv_invoices> pdv_invoices { get; set; }

    public virtual DbSet<pdv_mails> pdv_mails { get; set; }

    public virtual DbSet<vas_mails> vas_mails { get; set; }

    public virtual DbSet<vas_mailStatuses> vas_mailStatuses { get; set; }

    public virtual DbSet<vas_docStatusesLog> vas_docStatusesLog { get; set; }

    public virtual DbSet<vas_contractors> vas_contractors { get; set; }

    public virtual DbSet<vas_docStatuses> vas_docStatuses { get; set; }

    public virtual DbSet<vas_docTypes> vas_docTypes { get; set; }

    public virtual DbSet<vas_documents> vas_documents { get; set; }

    public virtual DbSet<vas_invoices> vas_invoices { get; set; }

    public virtual DbSet<vas_invoiceStatuses> vas_invoiceStatuses { get; set; }

    public virtual DbSet<vas_invoiceStatusesLog> vas_invoiceStatusesLog { get; set; }

    public virtual DbSet<vas_mailStatusesLog> vas_mailStatusesLog { get; set; }

    public virtual DbSet<tsilurik_contractors> tsilurik_contractors { get; set; }

    public virtual DbSet<tsilurik_documents> tsilurik_documents { get; set; }

    public virtual DbSet<tsilurik_invoices> tsilurik_invoices { get; set; }

    public virtual DbSet<tsilurik_mails> tsilurik_mails { get; set; }

    public virtual DbSet<tsilurik_status> tsilurik_status { get; set; }

    public virtual DbSet<tsilurik_statusLog> tsilurik_statusLog { get; set; }

    public virtual DbSet<tsilurik_types> tsilurik_types { get; set; }

    public virtual DbSet<gl_docs> gl_docs { get; set; }

    public virtual DbSet<pdv_documentType> pdv_documentType { get; set; }

    public virtual DbSet<pdv_deliveryService> pdv_deliveryService { get; set; }

    public virtual DbSet<pdv_deliveryMailStatuses> pdv_deliveryMailStatuses { get; set; }

    public virtual DbSet<pdv_invoiceStatuses> pdv_invoiceStatuses { get; set; }

    public virtual DbSet<pdv_documentStatusesLog> pdv_documentStatusesLog { get; set; }

    public virtual DbSet<pdv_documents> pdv_documents { get; set; }

    public virtual DbSet<fedchenko_counterparty> fedchenko_counterparty { get; set; }

    public virtual DbSet<fedchenko_docStatus> fedchenko_docStatus { get; set; }

    public virtual DbSet<fedchenko_docTypes> fedchenko_docTypes { get; set; }

    public virtual DbSet<fedchenko_documents> fedchenko_documents { get; set; }

    public virtual DbSet<fedchenko_invoices> fedchenko_invoices { get; set; }

    public virtual DbSet<fedchenko_invoiceStatus> fedchenko_invoiceStatus { get; set; }

    public virtual DbSet<fedchenko_mail> fedchenko_mail { get; set; }

    public virtual DbSet<fedchenko_mailStatus> fedchenko_mailStatus { get; set; }

    public virtual DbSet<motskin_contractors> motskin_contractors { get; set; }

    public virtual DbSet<motskin_documents> motskin_documents { get; set; }

    public virtual DbSet<motskin_documentStatuses> motskin_documentStatuses { get; set; }

    public virtual DbSet<motskin_documentStatusLog> motskin_documentStatusLog { get; set; }

    public virtual DbSet<motskin_documentTypes> motskin_documentTypes { get; set; }

    public virtual DbSet<motskin_invoices> motskin_invoices { get; set; }

    public virtual DbSet<motskin_invoiceStatuses> motskin_invoiceStatuses { get; set; }

    public virtual DbSet<motskin_invoiceStatusLog> motskin_invoiceStatusLog { get; set; }

    public virtual DbSet<motskin_mails> motskin_mails { get; set; }

    public virtual DbSet<motskin_mailStatuses> motskin_mailStatuses { get; set; }

    public virtual DbSet<motskin_mailStatusLog> motskin_mailStatusLog { get; set; }

    public virtual DbSet<motskin_sendSystems> motskin_sendSystems { get; set; }

    public virtual DbSet<molchanov_contragents> molchanov_contragents { get; set; }

    public virtual DbSet<molchanov_deliverySystems> molchanov_deliverySystems { get; set; }

    public virtual DbSet<molchanov_docStatuses> molchanov_docStatuses { get; set; }

    public virtual DbSet<molchanov_docTypes> molchanov_docTypes { get; set; }

    public virtual DbSet<molchanov_documents> molchanov_documents { get; set; }

    public virtual DbSet<molchanov_invoices> molchanov_invoices { get; set; }

    public virtual DbSet<molchanov_invoiceStatuses> molchanov_invoiceStatuses { get; set; }

    public virtual DbSet<molchanov_mails> molchanov_mails { get; set; }

    public virtual DbSet<molchanov_mailStatuses> molchanov_mailStatuses { get; set; }

    public virtual DbSet<udovika_contract> udovika_contract { get; set; }

    public virtual DbSet<udovika_contractor> udovika_contractor { get; set; }

    public virtual DbSet<udovika_contractType> udovika_contractType { get; set; }

    public virtual DbSet<udovika_documentStatusLog> udovika_documentStatusLog { get; set; }

    public virtual DbSet<udovika_email> udovika_email { get; set; }

    public virtual DbSet<udovika_invoice> udovika_invoice { get; set; }

    public virtual DbSet<udovika_statusContract> udovika_statusContract { get; set; }

    public virtual DbSet<udovika_statusEmail> udovika_statusEmail { get; set; }

    public virtual DbSet<udovika_statusInvoice> udovika_statusInvoice { get; set; }

    public virtual DbSet<molchanov_logContragents> molchanov_logContragents { get; set; }

    public virtual DbSet<molchanov_logDeliverySystems> molchanov_logDeliverySystems { get; set; }

    public virtual DbSet<molchanov_logDocStatuses> molchanov_logDocStatuses { get; set; }

    public virtual DbSet<molchanov_logDocTypes> molchanov_logDocTypes { get; set; }

    public virtual DbSet<molchanov_logDocuments> molchanov_logDocuments { get; set; }

    public virtual DbSet<molchanov_logInvoices> molchanov_logInvoices { get; set; }

    public virtual DbSet<molchanov_logInvoiceStatuses> molchanov_logInvoiceStatuses { get; set; }

    public virtual DbSet<molchanov_logMails> molchanov_logMails { get; set; }

    public virtual DbSet<molchanov_logMailStatuses> molchanov_logMailStatuses { get; set; }

    public virtual DbSet<rosh_contragents> rosh_contragents { get; set; }

    public virtual DbSet<rosh_contragentSources> rosh_contragentSources { get; set; }

    public virtual DbSet<rosh_contragentStatuses> rosh_contragentStatuses { get; set; }

    public virtual DbSet<rosh_docLogs> rosh_docLogs { get; set; }

    public virtual DbSet<rosh_docStatuses> rosh_docStatuses { get; set; }

    public virtual DbSet<rosh_docTypes> rosh_docTypes { get; set; }

    public virtual DbSet<rosh_documents> rosh_documents { get; set; }

    public virtual DbSet<rosh_mailLogs> rosh_mailLogs { get; set; }

    public virtual DbSet<rosh_mails> rosh_mails { get; set; }

    public virtual DbSet<rosh_mailStatuses> rosh_mailStatuses { get; set; }

    public virtual DbSet<rosh_orderLogs> rosh_orderLogs { get; set; }

    public virtual DbSet<rosh_orders> rosh_orders { get; set; }

    public virtual DbSet<rosh_orderStatuses> rosh_orderStatuses { get; set; }

    public virtual DbSet<rosh_sendingSystems> rosh_sendingSystems { get; set; }

    public virtual DbSet<rosh_CalendarEvents> rosh_CalendarEvents { get; set; }

    public virtual DbSet<rosh_sqlQueriesTable> rosh_sqlQueriesTable { get; set; }

    public virtual DbSet<h_contragents> h_contragents { get; set; }

    public virtual DbSet<h_deliverySystems> h_deliverySystems { get; set; }

    public virtual DbSet<h_docStatuses> h_docStatuses { get; set; }

    public virtual DbSet<h_docTypes> h_docTypes { get; set; }

    public virtual DbSet<h_invoiceStatuses> h_invoiceStatuses { get; set; }

    public virtual DbSet<h_mailStatuses> h_mailStatuses { get; set; }

    public virtual DbSet<h_invoices> h_invoices { get; set; }

    public virtual DbSet<h_mails> h_mails { get; set; }

    public virtual DbSet<h_logMails> h_logMails { get; set; }

    public virtual DbSet<h_documents> h_documents { get; set; }


    public virtual ObjectResult<GetPartners_Result> GetPartners(string sort1, string direction1, Nullable<int> page, string statusIDs, string specsIDs, Nullable<int> pageSize, string text, ObjectParameter total)
    {

        var sort1Parameter = sort1 != null ?
            new ObjectParameter("sort1", sort1) :
            new ObjectParameter("sort1", typeof(string));


        var direction1Parameter = direction1 != null ?
            new ObjectParameter("direction1", direction1) :
            new ObjectParameter("direction1", typeof(string));


        var pageParameter = page.HasValue ?
            new ObjectParameter("page", page) :
            new ObjectParameter("page", typeof(int));


        var statusIDsParameter = statusIDs != null ?
            new ObjectParameter("statusIDs", statusIDs) :
            new ObjectParameter("statusIDs", typeof(string));


        var specsIDsParameter = specsIDs != null ?
            new ObjectParameter("specsIDs", specsIDs) :
            new ObjectParameter("specsIDs", typeof(string));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("pageSize", pageSize) :
            new ObjectParameter("pageSize", typeof(int));


        var textParameter = text != null ?
            new ObjectParameter("text", text) :
            new ObjectParameter("text", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPartners_Result>("GetPartners", sort1Parameter, direction1Parameter, pageParameter, statusIDsParameter, specsIDsParameter, pageSizeParameter, textParameter, total);
    }


    public virtual int GetMailByDays(ObjectParameter days)
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMailByDays", days);
    }


    public virtual ObjectResult<GetMail_Result> GetMail(string type)
    {

        var typeParameter = type != null ?
            new ObjectParameter("type", type) :
            new ObjectParameter("type", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMail_Result>("GetMail", typeParameter);
    }


    public virtual int GetMailByMonth(Nullable<System.DateTime> curtMonth)
    {

        var curtMonthParameter = curtMonth.HasValue ?
            new ObjectParameter("curtMonth", curtMonth) :
            new ObjectParameter("curtMonth", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMailByMonth", curtMonthParameter);
    }


    public virtual ObjectResult<GetMailByWeeks_Result> GetMailByWeeks(Nullable<int> curMonth, Nullable<int> weeks)
    {

        var curMonthParameter = curMonth.HasValue ?
            new ObjectParameter("curMonth", curMonth) :
            new ObjectParameter("curMonth", typeof(int));


        var weeksParameter = weeks.HasValue ?
            new ObjectParameter("weeks", weeks) :
            new ObjectParameter("weeks", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMailByWeeks_Result>("GetMailByWeeks", curMonthParameter, weeksParameter);
    }


    public virtual ObjectResult<GetSite_Result> GetSite()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSite_Result>("GetSite");
    }


    public virtual ObjectResult<PDV_GetDocs_Result> PDV_GetDocs(string name, string number, string link, Nullable<int> documentTypeID, Nullable<int> documentStatusID, Nullable<int> contractorID, Nullable<System.DateTime> createdMin, Nullable<System.DateTime> createdMax, string sort1, string direction1, Nullable<int> page, Nullable<int> pageSize, ObjectParameter total)
    {

        var nameParameter = name != null ?
            new ObjectParameter("name", name) :
            new ObjectParameter("name", typeof(string));


        var numberParameter = number != null ?
            new ObjectParameter("number", number) :
            new ObjectParameter("number", typeof(string));


        var linkParameter = link != null ?
            new ObjectParameter("link", link) :
            new ObjectParameter("link", typeof(string));


        var documentTypeIDParameter = documentTypeID.HasValue ?
            new ObjectParameter("documentTypeID", documentTypeID) :
            new ObjectParameter("documentTypeID", typeof(int));


        var documentStatusIDParameter = documentStatusID.HasValue ?
            new ObjectParameter("documentStatusID", documentStatusID) :
            new ObjectParameter("documentStatusID", typeof(int));


        var contractorIDParameter = contractorID.HasValue ?
            new ObjectParameter("contractorID", contractorID) :
            new ObjectParameter("contractorID", typeof(int));


        var createdMinParameter = createdMin.HasValue ?
            new ObjectParameter("createdMin", createdMin) :
            new ObjectParameter("createdMin", typeof(System.DateTime));


        var createdMaxParameter = createdMax.HasValue ?
            new ObjectParameter("createdMax", createdMax) :
            new ObjectParameter("createdMax", typeof(System.DateTime));


        var sort1Parameter = sort1 != null ?
            new ObjectParameter("sort1", sort1) :
            new ObjectParameter("sort1", typeof(string));


        var direction1Parameter = direction1 != null ?
            new ObjectParameter("direction1", direction1) :
            new ObjectParameter("direction1", typeof(string));


        var pageParameter = page.HasValue ?
            new ObjectParameter("page", page) :
            new ObjectParameter("page", typeof(int));


        var pageSizeParameter = pageSize.HasValue ?
            new ObjectParameter("pageSize", pageSize) :
            new ObjectParameter("pageSize", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PDV_GetDocs_Result>("PDV_GetDocs", nameParameter, numberParameter, linkParameter, documentTypeIDParameter, documentStatusIDParameter, contractorIDParameter, createdMinParameter, createdMaxParameter, sort1Parameter, direction1Parameter, pageParameter, pageSizeParameter, total);
    }

}

}

