
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_comments
{

    public int id { get; set; }

    public string username { get; set; }

    public string text { get; set; }

    public Nullable<System.DateTime> created { get; set; }

    public string itemID { get; set; }

    public string type { get; set; }

    public string audio { get; set; }

}

}
