
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_images
{

    public int id { get; set; }

    public Nullable<int> itemID { get; set; }

    public string filename { get; set; }

    public Nullable<int> ord { get; set; }

    public string url { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string typeCode { get; set; }

}

}
