
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_mailLog
{

    public int id { get; set; }

    public string userName { get; set; }

    public Nullable<int> mailID { get; set; }

    public Nullable<System.DateTime> create { get; set; }



    public virtual as_mail as_mail { get; set; }

}

}
