
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_mt_metrics
{

    public as_mt_metrics()
    {

        this.as_mt_metrics1 = new HashSet<as_mt_metrics>();

    }


    public int id { get; set; }

    public string title { get; set; }

    public string subtitle { get; set; }

    public string sql { get; set; }

    public string parName { get; set; }

    public Nullable<int> parentID { get; set; }

    public Nullable<int> ord { get; set; }

    public Nullable<int> typeID { get; set; }

    public Nullable<bool> isSP { get; set; }

    public string users { get; set; }

    public string roles { get; set; }



    public virtual ICollection<as_mt_metrics> as_mt_metrics1 { get; set; }

    public virtual as_mt_metrics as_mt_metrics2 { get; set; }

    public virtual as_mt_metricTypes as_mt_metricTypes { get; set; }

}

}
