
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_mailAttachment
{

    public as_mailAttachment()
    {

        this.as_mail = new HashSet<as_mail>();

    }


    public int id { get; set; }

    public Nullable<int> mailID { get; set; }

    public Nullable<int> typeID { get; set; }

    public string link { get; set; }

    public string previewLink { get; set; }



    public virtual ICollection<as_mail> as_mail { get; set; }

    public virtual as_mail as_mail1 { get; set; }

    public virtual as_mailAttachmentType as_mailAttachmentType { get; set; }

}

}
