//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class as_mailingLog
    {
        public int id { get; set; }
        public int emailID { get; set; }
        public System.Guid userID { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual as_emails as_emails { get; set; }
        public virtual aspnet_Users aspnet_Users { get; set; }
    }
}
