
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_mailAttachmentType
{

    public as_mailAttachmentType()
    {

        this.as_mailAttachment = new HashSet<as_mailAttachment>();

    }


    public int id { get; set; }

    public string name { get; set; }



    public virtual ICollection<as_mailAttachment> as_mailAttachment { get; set; }

}

}
