
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_mt_metricTypes
{

    public as_mt_metricTypes()
    {

        this.as_mt_metrics = new HashSet<as_mt_metrics>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }

    public Nullable<int> ord { get; set; }



    public virtual ICollection<as_mt_metrics> as_mt_metrics { get; set; }

}

}
