
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_profileMenu
{

    public int id { get; set; }

    public string name { get; set; }

    public string href { get; set; }

    public string cssClass { get; set; }

    public Nullable<System.Guid> userGuid { get; set; }

}

}
