
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_sqlGet
{

    public as_sqlGet()
    {

        this.as_sqlRole = new HashSet<as_sqlRole>();

    }


    public int id { get; set; }

    public string code { get; set; }

    public string sql { get; set; }

    public string users { get; set; }



    public virtual ICollection<as_sqlRole> as_sqlRole { get; set; }

}

}
