
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_settings
{

    public as_settings()
    {

        this.as_settingAvailableValues = new HashSet<as_settingAvailableValues>();

    }


    public int id { get; set; }

    public string code { get; set; }

    public string value { get; set; }

    public Nullable<int> categoryID { get; set; }

    public Nullable<int> typeID { get; set; }

    public string value2 { get; set; }

    public string name { get; set; }



    public virtual as_dataTypes as_dataTypes { get; set; }

    public virtual ICollection<as_settingAvailableValues> as_settingAvailableValues { get; set; }

    public virtual as_settingCategories as_settingCategories { get; set; }

}

}
