
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_settingCategories
{

    public as_settingCategories()
    {

        this.as_settings = new HashSet<as_settings>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public Nullable<int> ord { get; set; }



    public virtual ICollection<as_settings> as_settings { get; set; }

}

}
