
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_textMistakes
{

    public int id { get; set; }

    public Nullable<System.Guid> userID { get; set; }

    public string selectText { get; set; }

    public string url { get; set; }

    public string comment { get; set; }

    public bool correct { get; set; }



    public virtual aspnet_Users aspnet_Users { get; set; }

}

}
