
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_userCheckSet
{

    public as_userCheckSet()
    {

        this.as_userCheckItems = new HashSet<as_userCheckItems>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }

    public string roles { get; set; }



    public virtual ICollection<as_userCheckItems> as_userCheckItems { get; set; }

}

}
