
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class as_userChecks
{

    public int id { get; set; }

    public string username { get; set; }

    public bool isClosed { get; set; }

    public string note { get; set; }

    public System.DateTime modifiedDate { get; set; }

    public int itemID { get; set; }



    public virtual as_userCheckItems as_userCheckItems { get; set; }

}

}
