
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class aspnet_Roles
{

    public aspnet_Roles()
    {

        this.aspnet_Users = new HashSet<aspnet_Users>();

    }


    public System.Guid ApplicationId { get; set; }

    public System.Guid RoleId { get; set; }

    public string RoleName { get; set; }

    public string LoweredRoleName { get; set; }

    public string Description { get; set; }



    public virtual aspnet_Applications aspnet_Applications { get; set; }

    public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }

}

}
