
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class aspnet_Profile
{

    public System.Guid UserId { get; set; }

    public string PropertyNames { get; set; }

    public string PropertyValuesString { get; set; }

    public byte[] PropertyValuesBinary { get; set; }

    public System.DateTime LastUpdatedDate { get; set; }



    public virtual aspnet_Users aspnet_Users { get; set; }

}

}
