
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class calc_parameters
{

    public int id { get; set; }

    public Nullable<int> calcID { get; set; }

    public string name { get; set; }

    public string code { get; set; }

    public string tooltip { get; set; }

    public Nullable<int> datatypeID { get; set; }

    public string defaultValue { get; set; }



    public virtual as_dataTypes as_dataTypes { get; set; }

    public virtual calc_calcs calc_calcs { get; set; }

}

}
