
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class cl_listInstanceItems
{

    public int id { get; set; }

    public System.DateTime modified { get; set; }

    public string modifiedBy { get; set; }

    public int listInstanceID { get; set; }

    public int listItemID { get; set; }

    public string value { get; set; }

    public bool isGood { get; set; }



    public virtual cl_listInstances cl_listInstances { get; set; }

    public virtual cl_listItems cl_listItems { get; set; }

}

}
