
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class cl_listInstances
{

    public cl_listInstances()
    {

        this.cl_listInstanceItems = new HashSet<cl_listInstanceItems>();

    }


    public int id { get; set; }

    public System.DateTime created { get; set; }

    public string createdBy { get; set; }

    public int itemID { get; set; }

    public int listID { get; set; }

    public string roles { get; set; }

    public string users { get; set; }



    public virtual ICollection<cl_listInstanceItems> cl_listInstanceItems { get; set; }

    public virtual cl_lists cl_lists { get; set; }

}

}
