
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class cl_lists
{

    public cl_lists()
    {

        this.cl_listInstances = new HashSet<cl_listInstances>();

        this.cl_listItems = new HashSet<cl_listItems>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }

    public string roles { get; set; }

    public string users { get; set; }



    public virtual ICollection<cl_listInstances> cl_listInstances { get; set; }

    public virtual ICollection<cl_listItems> cl_listItems { get; set; }

}

}
