
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class crm_orders
{

    public crm_orders()
    {

        this.crm_orderItems = new HashSet<crm_orderItems>();

    }


    public int id { get; set; }

    public Nullable<System.DateTime> created { get; set; }

    public string addedBy { get; set; }

    public string orderNum { get; set; }

    public Nullable<int> statusID { get; set; }

    public Nullable<int> clientID { get; set; }



    public virtual crm_clients crm_clients { get; set; }

    public virtual ICollection<crm_orderItems> crm_orderItems { get; set; }

    public virtual crm_orderStatuses crm_orderStatuses { get; set; }

}

}
