
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class crm_orderItems
{

    public int id { get; set; }

    public Nullable<int> orderID { get; set; }

    public Nullable<int> productID { get; set; }

    public Nullable<int> count { get; set; }

    public Nullable<decimal> price { get; set; }



    public virtual crm_orders crm_orders { get; set; }

    public virtual ct_products ct_products { get; set; }

}

}
