
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class ct_products
{

    public ct_products()
    {

        this.crm_orderItems = new HashSet<crm_orderItems>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public Nullable<decimal> price { get; set; }

    public string desc { get; set; }



    public virtual ICollection<crm_orderItems> crm_orderItems { get; set; }

}

}
