
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class doc_docs
{

    public doc_docs()
    {

        this.doc_docLogs = new HashSet<doc_docLogs>();

        this.doc_docVersions = new HashSet<doc_docVersions>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public System.DateTime created { get; set; }

    public string number { get; set; }

    public string path { get; set; }

    public int projectID { get; set; }

    public int contragentID { get; set; }

    public int statusID { get; set; }

    public int typeID { get; set; }

    public System.Guid createdBy { get; set; }



    public virtual ICollection<doc_docLogs> doc_docLogs { get; set; }

    public virtual doc_docStatuses doc_docStatuses { get; set; }

    public virtual doc_docTypes doc_docTypes { get; set; }

    public virtual fin_contragents fin_contragents { get; set; }

    public virtual tt_projects tt_projects { get; set; }

    public virtual ICollection<doc_docVersions> doc_docVersions { get; set; }

}

}
