
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class doc_docTypes
{

    public doc_docTypes()
    {

        this.doc_docTypeTemplates = new HashSet<doc_docTypeTemplates>();

        this.doc_docs = new HashSet<doc_docs>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }



    public virtual ICollection<doc_docTypeTemplates> doc_docTypeTemplates { get; set; }

    public virtual ICollection<doc_docs> doc_docs { get; set; }

}

}
