
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class fedchenko_invoiceStatus
{

    public fedchenko_invoiceStatus()
    {

        this.fedchenko_invoices = new HashSet<fedchenko_invoices>();

    }


    public int Id { get; set; }

    public string Name { get; set; }



    public virtual ICollection<fedchenko_invoices> fedchenko_invoices { get; set; }

}

}
