
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class fedchenko_docStatus
{

    public fedchenko_docStatus()
    {

        this.fedchenko_documents = new HashSet<fedchenko_documents>();

    }


    public int Id { get; set; }

    public string Name { get; set; }



    public virtual ICollection<fedchenko_documents> fedchenko_documents { get; set; }

}

}
