
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class fedchenko_invoices
{

    public int Id { get; set; }

    public string Number { get; set; }

    public int CounterpartyId { get; set; }

    public string Comment { get; set; }

    public int InvoiceStaus { get; set; }



    public virtual fedchenko_counterparty fedchenko_counterparty { get; set; }

    public virtual fedchenko_invoiceStatus fedchenko_invoiceStatus { get; set; }

}

}
