
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class fedchenko_mail
{

    public int Id { get; set; }

    public Nullable<int> MailStatus { get; set; }

    public System.DateTime Date { get; set; }

    public string From { get; set; }

    public string To { get; set; }

    public string Description { get; set; }

    public string SendingSystem { get; set; }

    public string TrackNumber { get; set; }

    public string TrackNumberBack { get; set; }

    public System.DateTime DateBack { get; set; }



    public virtual fedchenko_mailStatus fedchenko_mailStatus { get; set; }

}

}
