
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class fin_contragents
{

    public fin_contragents()
    {

        this.fin_finances = new HashSet<fin_finances>();

        this.fin_finances1 = new HashSet<fin_finances>();

        this.doc_docs = new HashSet<doc_docs>();

        this.gl_docs = new HashSet<gl_docs>();

    }


    public int id { get; set; }

    public Nullable<int> humanID { get; set; }

    public Nullable<int> clientID { get; set; }

    public string name { get; set; }



    public virtual crm_clients crm_clients { get; set; }

    public virtual hr_humans hr_humans { get; set; }

    public virtual ICollection<fin_finances> fin_finances { get; set; }

    public virtual ICollection<fin_finances> fin_finances1 { get; set; }

    public virtual ICollection<doc_docs> doc_docs { get; set; }

    public virtual ICollection<gl_docs> gl_docs { get; set; }

}

}
