
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class fin_finances
{

    public int id { get; set; }

    public Nullable<System.DateTime> created { get; set; }

    public Nullable<int> fromID { get; set; }

    public Nullable<int> toID { get; set; }

    public string desc { get; set; }

    public Nullable<int> channelID { get; set; }

    public Nullable<decimal> sum { get; set; }

    public Nullable<int> projectID { get; set; }

    public Nullable<int> typeID { get; set; }

    public Nullable<int> statusID { get; set; }



    public virtual fin_channels fin_channels { get; set; }

    public virtual fin_contragents fin_contragents { get; set; }

    public virtual fin_contragents fin_contragents1 { get; set; }

    public virtual fin_statuses fin_statuses { get; set; }

    public virtual fin_types fin_types { get; set; }

    public virtual tt_projects tt_projects { get; set; }

}

}
