
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class fin_statuses
{

    public fin_statuses()
    {

        this.fin_finances = new HashSet<fin_finances>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }

    public string color { get; set; }



    public virtual ICollection<fin_finances> fin_finances { get; set; }

}

}
