
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class gr_site
{

    public int id { get; set; }

    public Nullable<int> visit { get; set; }

    public Nullable<int> download { get; set; }

    public Nullable<int> query { get; set; }

    public Nullable<int> cheque { get; set; }

    public Nullable<int> pay { get; set; }

}

}
