
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class gurevskiy_contracts
{

    public int id { get; set; }

    public int typeID { get; set; }

    public int statusID { get; set; }

    public int partnerID { get; set; }

    public System.DateTime date { get; set; }

    public string number { get; set; }

    public Nullable<decimal> sum { get; set; }

    public string comment { get; set; }

    public string link { get; set; }



    public virtual gurevskiy_contractStatuses gurevskiy_contractStatuses { get; set; }

    public virtual gurevskiy_contractTypes gurevskiy_contractTypes { get; set; }

    public virtual gurevskiy_partner gurevskiy_partner { get; set; }

}

}
