
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class gurevskiy_mails
{

    public int id { get; set; }

    public int statusID { get; set; }

    public System.DateTime date { get; set; }

    public string from { get; set; }

    public string to { get; set; }

    public string desc { get; set; }

    public string systemSending { get; set; }

    public string numberTrack { get; set; }

    public string numberTrackBack { get; set; }

    public Nullable<System.DateTime> dateBack { get; set; }



    public virtual gurevskiy_mailStatuses gurevskiy_mailStatuses { get; set; }

}

}
