
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class h_contragents
{

    public h_contragents()
    {

        this.h_invoices = new HashSet<h_invoices>();

        this.h_documents = new HashSet<h_documents>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string email { get; set; }



    public virtual ICollection<h_invoices> h_invoices { get; set; }

    public virtual ICollection<h_documents> h_documents { get; set; }

}

}
