
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class h_documents
{

    public h_documents()
    {

        this.h_documents1 = new HashSet<h_documents>();

    }


    public int id { get; set; }

    public System.Guid uniqueCode { get; set; }

    public System.DateTime date { get; set; }

    public string number { get; set; }

    public decimal sum { get; set; }

    public string description { get; set; }

    public string link { get; set; }

    public int contragentID { get; set; }

    public int docTypeID { get; set; }

    public int docStatusID { get; set; }

    public Nullable<int> docParentID { get; set; }

    public bool isDeleted { get; set; }



    public virtual h_contragents h_contragents { get; set; }

    public virtual h_docStatuses h_docStatuses { get; set; }

    public virtual h_docTypes h_docTypes { get; set; }

    public virtual ICollection<h_documents> h_documents1 { get; set; }

    public virtual h_documents h_documents2 { get; set; }

}

}
