
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class h_invoices
{

    public int id { get; set; }

    public Nullable<System.Guid> uniqueCode { get; set; }

    public System.DateTime date { get; set; }

    public string number { get; set; }

    public string description { get; set; }

    public Nullable<int> invStatusID { get; set; }

    public Nullable<int> contragentID { get; set; }

    public bool isDeleted { get; set; }



    public virtual h_contragents h_contragents { get; set; }

    public virtual h_invoiceStatuses h_invoiceStatuses { get; set; }

}

}
