
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class h_mails
{

    public h_mails()
    {

        this.h_logMails = new HashSet<h_logMails>();

    }


    public int id { get; set; }

    public Nullable<System.Guid> uniqueCode { get; set; }

    public System.DateTime date { get; set; }

    public string fromSender { get; set; }

    public string toRecipient { get; set; }

    public string description { get; set; }

    public string trackNumber { get; set; }

    public string backTrackNumber { get; set; }

    public Nullable<System.DateTime> backDateRecipient { get; set; }

    public Nullable<int> deliverySystemID { get; set; }

    public Nullable<int> mailStatusID { get; set; }



    public virtual h_deliverySystems h_deliverySystems { get; set; }

    public virtual h_mailStatuses h_mailStatuses { get; set; }

    public virtual ICollection<h_logMails> h_logMails { get; set; }

}

}
