
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class hr_humanSpecializations
{

    public int id { get; set; }

    public Nullable<int> humanID { get; set; }

    public Nullable<int> specializationID { get; set; }



    public virtual hr_humans hr_humans { get; set; }

    public virtual hr_specializations hr_specializations { get; set; }

}

}
