
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class hr_humans
{

    public hr_humans()
    {

        this.hr_humanSpecializations = new HashSet<hr_humanSpecializations>();

        this.fin_contragents = new HashSet<fin_contragents>();

    }


    public int id { get; set; }

    public Nullable<int> sourceID { get; set; }

    public Nullable<int> statusID { get; set; }

    public Nullable<System.DateTime> created { get; set; }

    public string contacts { get; set; }

    public string fio { get; set; }

    public string note { get; set; }

    public string addedBy { get; set; }

    public string subchannel { get; set; }

    public string username { get; set; }

    public string city { get; set; }

    public Nullable<bool> needActive { get; set; }

    public Nullable<System.Guid> sourceGuid { get; set; }

    public string pay { get; set; }

    public Nullable<decimal> hourRate { get; set; }



    public virtual hr_sources hr_sources { get; set; }

    public virtual hr_statuses hr_statuses { get; set; }

    public virtual ICollection<hr_humanSpecializations> hr_humanSpecializations { get; set; }

    public virtual ICollection<fin_contragents> fin_contragents { get; set; }

}

}
