
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class hr_sources
{

    public hr_sources()
    {

        this.hr_humans = new HashSet<hr_humans>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string note { get; set; }

    public string code { get; set; }



    public virtual ICollection<hr_humans> hr_humans { get; set; }

}

}
