
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class imp_items
{

    public imp_items()
    {

        this.imp_itemLog = new HashSet<imp_itemLog>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }

    public string datatable { get; set; }

    public string sqlInsert { get; set; }

    public string sqlUpdate { get; set; }

    public string sqlDelete { get; set; }



    public virtual ICollection<imp_itemLog> imp_itemLog { get; set; }

}

}
