
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class Mikhailova_contracts
{

    public int id { get; set; }

    public string number { get; set; }

    public System.DateTime date { get; set; }

    public int contagentID { get; set; }

    public decimal summa { get; set; }

    public string desc { get; set; }

    public int statusID { get; set; }

    public string path { get; set; }

    public Nullable<int> typeID { get; set; }

    public Nullable<bool> isDeleted { get; set; }



    public virtual Mikhailova_contagents Mikhailova_contagents { get; set; }

    public virtual Mikhailova_statuses_contracts Mikhailova_statuses_contracts { get; set; }

    public virtual Mikhailova_docTypes Mikhailova_docTypes { get; set; }

}

}
