
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class Mikhailova_invoices
{

    public int id { get; set; }

    public System.DateTime date { get; set; }

    public string number { get; set; }

    public int contagentID { get; set; }

    public string desc { get; set; }

    public int statusID { get; set; }

    public Nullable<bool> isDeleted { get; set; }



    public virtual Mikhailova_contagents Mikhailova_contagents { get; set; }

    public virtual Mikhailova_statuses_invoces Mikhailova_statuses_invoces { get; set; }

}

}
