
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class molchanov_invoiceStatuses
{

    public molchanov_invoiceStatuses()
    {

        this.molchanov_invoices = new HashSet<molchanov_invoices>();

        this.molchanov_logInvoiceStatuses = new HashSet<molchanov_logInvoiceStatuses>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }



    public virtual ICollection<molchanov_invoices> molchanov_invoices { get; set; }

    public virtual ICollection<molchanov_logInvoiceStatuses> molchanov_logInvoiceStatuses { get; set; }

}

}
