
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class molchanov_contragents
{

    public molchanov_contragents()
    {

        this.molchanov_invoices = new HashSet<molchanov_invoices>();

        this.molchanov_documents = new HashSet<molchanov_documents>();

        this.molchanov_logContragents = new HashSet<molchanov_logContragents>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string email { get; set; }



    public virtual ICollection<molchanov_invoices> molchanov_invoices { get; set; }

    public virtual ICollection<molchanov_documents> molchanov_documents { get; set; }

    public virtual ICollection<molchanov_logContragents> molchanov_logContragents { get; set; }

}

}
