
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class molchanov_logDocStatuses
{

    public int id { get; set; }

    public System.DateTime date { get; set; }

    public string notice { get; set; }

    public string userName { get; set; }

    public int docStatusID { get; set; }



    public virtual molchanov_docStatuses molchanov_docStatuses { get; set; }

}

}
