
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class motskin_sendSystems
{

    public motskin_sendSystems()
    {

        this.motskin_mails = new HashSet<motskin_mails>();

    }


    public int id { get; set; }

    public string name { get; set; }



    public virtual ICollection<motskin_mails> motskin_mails { get; set; }

}

}
