
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class motskin_contractors
{

    public motskin_contractors()
    {

        this.motskin_documents = new HashSet<motskin_documents>();

        this.motskin_invoices = new HashSet<motskin_invoices>();

    }


    public int id { get; set; }

    public string name { get; set; }



    public virtual ICollection<motskin_documents> motskin_documents { get; set; }

    public virtual ICollection<motskin_invoices> motskin_invoices { get; set; }

}

}
