
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class motskin_invoiceStatuses
{

    public motskin_invoiceStatuses()
    {

        this.motskin_invoices = new HashSet<motskin_invoices>();

        this.motskin_invoiceStatusLog = new HashSet<motskin_invoiceStatusLog>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }



    public virtual ICollection<motskin_invoices> motskin_invoices { get; set; }

    public virtual ICollection<motskin_invoiceStatusLog> motskin_invoiceStatusLog { get; set; }

}

}
