
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class motskin_invoices
{

    public motskin_invoices()
    {

        this.motskin_invoiceStatusLog = new HashSet<motskin_invoiceStatusLog>();

    }


    public int id { get; set; }

    public System.DateTime date { get; set; }

    public string number { get; set; }

    public string comment { get; set; }

    public bool isDeleted { get; set; }

    public int contractorID { get; set; }

    public int invoiceStatusID { get; set; }

    public System.Guid createdUnique { get; set; }



    public virtual motskin_contractors motskin_contractors { get; set; }

    public virtual ICollection<motskin_invoiceStatusLog> motskin_invoiceStatusLog { get; set; }

    public virtual motskin_invoiceStatuses motskin_invoiceStatuses { get; set; }

}

}
