
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class motskin_invoiceStatusLog
{

    public int id { get; set; }

    public System.DateTime created { get; set; }

    public string note { get; set; }

    public int invoiceStatusID { get; set; }

    public int invoiceID { get; set; }



    public virtual motskin_invoices motskin_invoices { get; set; }

    public virtual motskin_invoiceStatuses motskin_invoiceStatuses { get; set; }

}

}
