
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class motskin_mailStatuses
{

    public motskin_mailStatuses()
    {

        this.motskin_mails = new HashSet<motskin_mails>();

        this.motskin_mailStatusLog = new HashSet<motskin_mailStatusLog>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }



    public virtual ICollection<motskin_mails> motskin_mails { get; set; }

    public virtual ICollection<motskin_mailStatusLog> motskin_mailStatusLog { get; set; }

}

}
