
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class pdv_invoices
{

    public int id { get; set; }

    public System.DateTime createDate { get; set; }

    public Nullable<int> number { get; set; }

    public Nullable<int> contractorID { get; set; }

    public string comment { get; set; }

    public Nullable<int> invoiceStatusID { get; set; }

    public Nullable<int> documentID { get; set; }

    public bool isDeleted { get; set; }



    public virtual pdv_contractors pdv_contractors { get; set; }

    public virtual pdv_invoiceStatuses pdv_invoiceStatuses { get; set; }

    public virtual pdv_documents pdv_documents { get; set; }

}

}
