
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class pdv_mails
{

    public int id { get; set; }

    public System.DateTime createDate { get; set; }

    public Nullable<int> contractorFromID { get; set; }

    public Nullable<int> contractorToID { get; set; }

    public string description { get; set; }

    public Nullable<int> deliveryServiceID { get; set; }

    public Nullable<int> trackNumber { get; set; }

    public Nullable<int> deleveryStatusID { get; set; }

    public Nullable<int> reTrackNumber { get; set; }

    public Nullable<System.DateTime> reDateOfReceiving { get; set; }

    public bool isDeleted { get; set; }



    public virtual pdv_contractors pdv_contractors { get; set; }

    public virtual pdv_contractors pdv_contractors1 { get; set; }

    public virtual pdv_deliveryService pdv_deliveryService { get; set; }

    public virtual pdv_deliveryMailStatuses pdv_deliveryMailStatuses { get; set; }

}

}
