
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class pdv_documentStatusesLog
{

    public int id { get; set; }

    public System.DateTime created { get; set; }

    public int statusID { get; set; }

    public int documentID { get; set; }

    public string note { get; set; }

}

}
