
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class pdv_contractors
{

    public pdv_contractors()
    {

        this.pdv_invoices = new HashSet<pdv_invoices>();

        this.pdv_mails = new HashSet<pdv_mails>();

        this.pdv_mails1 = new HashSet<pdv_mails>();

        this.pdv_documents = new HashSet<pdv_documents>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public Nullable<bool> isDeleted { get; set; }



    public virtual ICollection<pdv_invoices> pdv_invoices { get; set; }

    public virtual ICollection<pdv_mails> pdv_mails { get; set; }

    public virtual ICollection<pdv_mails> pdv_mails1 { get; set; }

    public virtual ICollection<pdv_documents> pdv_documents { get; set; }

}

}
