//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class podvashetskyi_invoices
    {
        public int id { get; set; }
        public System.DateTime createDate { get; set; }
        public int number { get; set; }
        public int contractorID { get; set; }
        public string comment { get; set; }
        public int statusInvoiceID { get; set; }
    
        public virtual podvashetskyi_contractors podvashetskyi_contractors { get; set; }
        public virtual podvashetskyi_statuses_for_invoices podvashetskyi_statuses_for_invoices { get; set; }
    }
}
