//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class podvashetskyi_contractors
    {
        public podvashetskyi_contractors()
        {
            this.podvashetskyi_documents = new HashSet<podvashetskyi_documents>();
            this.podvashetskyi_invoices = new HashSet<podvashetskyi_invoices>();
            this.podvashetskyi_mails = new HashSet<podvashetskyi_mails>();
            this.podvashetskyi_mails1 = new HashSet<podvashetskyi_mails>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual podvashetskyi_contractors podvashetskyi_contractors1 { get; set; }
        public virtual podvashetskyi_contractors podvashetskyi_contractors2 { get; set; }
        public virtual ICollection<podvashetskyi_documents> podvashetskyi_documents { get; set; }
        public virtual ICollection<podvashetskyi_invoices> podvashetskyi_invoices { get; set; }
        public virtual ICollection<podvashetskyi_mails> podvashetskyi_mails { get; set; }
        public virtual ICollection<podvashetskyi_mails> podvashetskyi_mails1 { get; set; }
    }
}
