//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class podvashetskyi_mails
    {
        public int id { get; set; }
        public System.DateTime createDate { get; set; }
        public int contractorFromID { get; set; }
        public int contractorWhereID { get; set; }
        public string description { get; set; }
        public string deliveryService { get; set; }
        public int trackNumber { get; set; }
        public int statusMailID { get; set; }
        public int reTrackNumber { get; set; }
        public System.DateTime reDateOfReceiving { get; set; }
    
        public virtual podvashetskyi_contractors podvashetskyi_contractors { get; set; }
        public virtual podvashetskyi_contractors podvashetskyi_contractors1 { get; set; }
        public virtual podvashetskyi_statuses_for_mails podvashetskyi_statuses_for_mails { get; set; }
    }
}
