
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class proc_processItems
{

    public int id { get; set; }

    public int processID { get; set; }

    public int ord { get; set; }

    public string name { get; set; }

    public string desc { get; set; }

    public string roles { get; set; }

    public string users { get; set; }

    public bool isFinish { get; set; }

    public string color { get; set; }



    public virtual proc_processes proc_processes { get; set; }

}

}
