
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class ps_specsPartners
{

    public int id { get; set; }

    public Nullable<int> specID { get; set; }

    public Nullable<int> partnerID { get; set; }



    public virtual ps_partners ps_partners { get; set; }

    public virtual ps_specs ps_specs { get; set; }

}

}
