
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class ps_statuses
{

    public ps_statuses()
    {

        this.ps_partners = new HashSet<ps_partners>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string code { get; set; }

    public string color { get; set; }

    public string order { get; set; }



    public virtual ICollection<ps_partners> ps_partners { get; set; }

}

}
