
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class ps_specs
{

    public ps_specs()
    {

        this.ps_specsPartners = new HashSet<ps_specsPartners>();

    }


    public int id { get; set; }

    public string name { get; set; }



    public virtual ICollection<ps_specsPartners> ps_specsPartners { get; set; }

}

}
