
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class recl_items
{

    public int id { get; set; }

    public string name { get; set; }

    public string customerText { get; set; }

    public string whatToDo { get; set; }

    public Nullable<System.DateTime> created { get; set; }

    public string addedBy { get; set; }

    public Nullable<System.DateTime> reportDate { get; set; }

    public Nullable<int> statusID { get; set; }

    public Nullable<int> projectID { get; set; }

    public bool haveWOW { get; set; }

    public string report { get; set; }



    public virtual recl_itemStatuses recl_itemStatuses { get; set; }

    public virtual tt_projects tt_projects { get; set; }

}

}
