
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class rosh_sqlQueriesTable
{

    public int id { get; set; }

    public string con { get; set; }

    public string manager { get; set; }

    public int timeLimit { get; set; }

    public int rowsLimit { get; set; }

}

}
