
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class rosh_CalendarEvents
{

    public int id { get; set; }

    public string title { get; set; }

    public string description { get; set; }

    public System.DateTime startEvent { get; set; }

    public System.DateTime endEvent { get; set; }

    public int eventTypeID { get; set; }

}

}
