
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class rosh_documents
{

    public rosh_documents()
    {

        this.rosh_docLogs = new HashSet<rosh_docLogs>();

    }


    public int id { get; set; }

    public int docTypeID { get; set; }

    public System.DateTime docDate { get; set; }

    public string docNumber { get; set; }

    public Nullable<int> orderID { get; set; }

    public decimal amount { get; set; }

    public int docStatusID { get; set; }

    public string description { get; set; }

    public int contragentID { get; set; }



    public virtual rosh_contragents rosh_contragents { get; set; }

    public virtual ICollection<rosh_docLogs> rosh_docLogs { get; set; }

    public virtual rosh_docStatuses rosh_docStatuses { get; set; }

    public virtual rosh_docTypes rosh_docTypes { get; set; }

    public virtual rosh_orders rosh_orders { get; set; }

}

}
