
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class rosh_sendingSystems
{

    public rosh_sendingSystems()
    {

        this.rosh_mails = new HashSet<rosh_mails>();

    }


    public int id { get; set; }

    public string name { get; set; }



    public virtual ICollection<rosh_mails> rosh_mails { get; set; }

}

}
