
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class rosh_mails
{

    public rosh_mails()
    {

        this.rosh_mailLogs = new HashSet<rosh_mailLogs>();

    }


    public int id { get; set; }

    public System.DateTime date { get; set; }

    public Nullable<int> orderID { get; set; }

    public string fromAdress { get; set; }

    public string toAdress { get; set; }

    public string description { get; set; }

    public int sendingSystemID { get; set; }

    public string truckNumber { get; set; }

    public int mailStatusID { get; set; }

    public string backTruckNumber { get; set; }

    public Nullable<System.DateTime> backReceivedDate { get; set; }



    public virtual ICollection<rosh_mailLogs> rosh_mailLogs { get; set; }

    public virtual rosh_mailStatuses rosh_mailStatuses { get; set; }

    public virtual rosh_orders rosh_orders { get; set; }

    public virtual rosh_sendingSystems rosh_sendingSystems { get; set; }

}

}
