
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class rosh_contragentSources
{

    public rosh_contragentSources()
    {

        this.rosh_contragents = new HashSet<rosh_contragents>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string description { get; set; }



    public virtual ICollection<rosh_contragents> rosh_contragents { get; set; }

}

}
