
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class tsilurik_documents
{

    public tsilurik_documents()
    {

        this.tsilurik_statusLog = new HashSet<tsilurik_statusLog>();

    }


    public int id { get; set; }

    public System.DateTime date { get; set; }

    public string number { get; set; }

    public int contractorID { get; set; }

    public decimal sum { get; set; }

    public string note { get; set; }

    public int statusID { get; set; }

    public int typeID { get; set; }

    public string link { get; set; }



    public virtual tsilurik_contractors tsilurik_contractors { get; set; }

    public virtual tsilurik_status tsilurik_status { get; set; }

    public virtual tsilurik_types tsilurik_types { get; set; }

    public virtual ICollection<tsilurik_statusLog> tsilurik_statusLog { get; set; }

}

}
