
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class tsilurik_status
{

    public tsilurik_status()
    {

        this.tsilurik_documents = new HashSet<tsilurik_documents>();

        this.tsilurik_invoices = new HashSet<tsilurik_invoices>();

        this.tsilurik_mails = new HashSet<tsilurik_mails>();

        this.tsilurik_statusLog = new HashSet<tsilurik_statusLog>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string note { get; set; }



    public virtual ICollection<tsilurik_documents> tsilurik_documents { get; set; }

    public virtual ICollection<tsilurik_invoices> tsilurik_invoices { get; set; }

    public virtual ICollection<tsilurik_mails> tsilurik_mails { get; set; }

    public virtual ICollection<tsilurik_statusLog> tsilurik_statusLog { get; set; }

}

}
