
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class tsilurik_mails
{

    public tsilurik_mails()
    {

        this.tsilurik_statusLog = new HashSet<tsilurik_statusLog>();

    }


    public int id { get; set; }

    public System.DateTime date { get; set; }

    public string from { get; set; }

    public string to { get; set; }

    public string description { get; set; }

    public string mailSystem { get; set; }

    public string trackNumber { get; set; }

    public int statusID { get; set; }

    public string returnTrackNumber { get; set; }

    public Nullable<System.DateTime> returnDate { get; set; }



    public virtual tsilurik_status tsilurik_status { get; set; }

    public virtual ICollection<tsilurik_statusLog> tsilurik_statusLog { get; set; }

}

}
