
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class tst_cars
{

    public int id { get; set; }

    public string description { get; set; }

    public Nullable<int> created { get; set; }

    public Nullable<int> driverID { get; set; }



    public virtual tst_drivers tst_drivers { get; set; }

}

}
