
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class tst_drivers
{

    public tst_drivers()
    {

        this.tst_cars = new HashSet<tst_cars>();

    }


    public int id { get; set; }

    public string name { get; set; }



    public virtual ICollection<tst_cars> tst_cars { get; set; }

}

}
