
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class udovika_contract
{

    public int id { get; set; }

    public System.DateTime date { get; set; }

    public string number { get; set; }

    public int contractorID { get; set; }

    public decimal total { get; set; }

    public string comment { get; set; }

    public int statusID { get; set; }

    public int typeID { get; set; }

    public string link { get; set; }



    public virtual udovika_contractor udovika_contractor { get; set; }

    public virtual udovika_contractType udovika_contractType { get; set; }

    public virtual udovika_statusContract udovika_statusContract { get; set; }

}

}
