
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace arkAS.BLL
{

using System;
    using System.Collections.Generic;
    
public partial class vas_mails
{

    public int id { get; set; }

    public System.DateTime date { get; set; }

    public string from { get; set; }

    public string to { get; set; }

    public string comment { get; set; }

    public string mailSystem { get; set; }

    public string trackNumber { get; set; }

    public string trackNumberRepay { get; set; }

    public Nullable<System.DateTime> dateReplay { get; set; }

    public int statusID { get; set; }

    public string code { get; set; }



    public virtual vas_mailStatuses vas_mailStatuses { get; set; }

}

}
