//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arkAS.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vas_mail
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string comment { get; set; }
        public string mailSystem { get; set; }
        public string trackNumber { get; set; }
        public string trackNumberRepay { get; set; }
        public System.DateTime dateReplay { get; set; }
        public Nullable<int> statusID { get; set; }
    
        public virtual vas_mailStatus vas_mailStatuses { get; set; }
    }
}
